name: Bug Report
description: Report a bug or issue with this project
title: "[Bug]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report

  - type: input
    id: summary
    attributes:
      label: Bug Summary
      description: Briefly describe the bug you are experiencing.
      placeholder: Add a short summary of the bug
    validations:
      required: true